version: '3.8'

services:
  db:
    image: mariadb:10.5
    container_name: app_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: app_db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: app_backend
    restart: always
    environment:
      DATABASE_URL: mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db/app_db
      FLASK_APP: app.py
      FLASK_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: app_frontend
    restart: always
    ports:
      - "4000:4000"
    environment:
      BACKEND_URL: http://backend:3000
      PORT: 4000
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mariadb_data: