version: '3.8'

services:
  db:
    image: mariadb:10.5
    container_name: app_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: app_db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass123
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: app_backend
    restart: always
    environment:
      DATABASE_URL: mysql+pymysql://dbuser:dbpass123@db/app_db
      FLASK_APP: app.py
      FLASK_ENV: development
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: app_frontend
    restart: always
    ports:
      - "8001:8000"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mariadb_data:
